services:
  db:
    image: postgres:13
    container_name: ecommerce_db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: ecommerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce_app
    environment:
      - DB_HOST=db
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=ecommerce
      - DB_PORT=5432
    depends_on:
      - db
    ports:
      - "8080:8080"
    command: ["./main"]

volumes:
  postgres_data:
